import os
from dotenv import load_dotenv

load_dotenv()

URLHAUS_API_KEY = os.getenv("URLHAUS_API_KEY")
MALWAREBAZAAR_API_KEY = os.getenv("MALWAREBAZAAR_API_KEY")
ALIENVAULT_OTX_API_KEY = os.getenv("ALIENVAULT_OTX_API_KEY")
VIRUSTOTAL_API_KEY = os.getenv("VIRUSTOTAL_API_KEY")
URLSCAN_API_KEY = os.getenv("URLSCAN_API_KEY")
SECURITYTRAILS_API_KEY = os.getenv("SECURITYTRAILS_API_KEY")
LEAKCHECK_API_KEY = os.getenv("LEAKCHECK_API_KEY")
